# Generated by Django 5.1.5 on 2025-08-08 18:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('INCOME', 'درآمد'), ('EXPENSE', 'مخارج')], default='EXPENSE', max_length=20),
        ),
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 8, 8, 18, 48, 53, 694093, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
