# Generated by Django 5.1.5 on 2025-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='currency',
            field=models.CharField(choices=[('IRR', 'ریال'), ('IRT', 'تومان'), ('USD', 'دلار')], default='IRT', max_length=20),
        ),
    ]
