# Generated by Django 5.1.5 on 2025-07-12 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('collection', '0001_initial'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='collection.collection', verbose_name='what is the user right now'),
        ),
    ]
