# Generated by Django 5.1.5 on 2025-05-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('expense', '0002_alter_collection_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='collection.collection'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
